#springboot整合Mybatis相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.tang.domain # 配置哪个包下的类有默认的别名





#
#name: tangzhengxiang
#age: 17
#date: 2021/9/9
#
#student:
#  lastName: tang
#  age: 15
#  boss: true
#  birthday: 2001/2/3
#  maps:
#    name: tang
#    age: 11
#  maps2: {name: ttt, age: 199}
#  list:
#    - name: 小白
#      age: 3
#    - name: 小黄
#      age: 4
#    - {name: 小黑, age: 1}
#  dog:
#    name: 小红
#    age: 5
#  arr:
#    - tang
#    - ttt
#  arr2: [tang, ttt]
#  dogMap:
#    xb: {name: 小白, age: 9}
#    xh:
#      name: 小红
#      age: 6
#
