server:
  port: 8081
#springboot整合Mybatis相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    proxy-target-class: true
  redis:
    port: 6379
    host: 127.0.0.1

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.tang.domain # 配置哪个包下的类有默认的别名
